//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azi.Cloud.DokanNet.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azi.Cloud.DokanNet.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon app_all {
            get {
                object obj = ResourceManager.GetObject("app_all", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file can be created only if you start application As Administrator at least once.
        ///Log file may contain some private information like folder and file names. But application does not know your email or Amazon Cloud Drive password.
        ///You can open log file in standard Windows Event Viewer just double clicking the file..
        /// </summary>
        public static string LogWarning {
            get {
                return ResourceManager.GetString("LogWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Errors and Warnings will be sent.
        ///It does not contain file content or cloud account info, not even account login basicly because it does not know neither login nor password. 
        ///Still It may contain some private info like names of folders or files.
        ///
        ///You can always disable Telemetry clicking checkbox again. Also checkbox will be unchecked on next app start.
        ///.
        /// </summary>
        public static string SendTelemetryTooltip {
            get {
                return ResourceManager.GetString("SendTelemetryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of all small files in cache..
        /// </summary>
        public static string SmallFileCacheSizeTooltip {
            get {
                return ResourceManager.GetString("SmallFileCacheSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size of files which will be cached whole on first request..
        /// </summary>
        public static string SmallFileSizeTooltip {
            get {
                return ResourceManager.GetString("SmallFileSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow Amazon Cloud Drive login page in your browser and retrun here after it&apos;s complete..
        /// </summary>
        public static string WaitForRedirectMessage {
            get {
                return ResourceManager.GetString("WaitForRedirectMessage", resourceCulture);
            }
        }
    }
}
